name: coins_price_yemen
description: Coins Price Yemen.

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  html: ^0.15.3
  dio: ^5.1.2
  url_launcher: ^6.1.11
  share_plus: ^7.0.0
  date_format: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.19
  flutter_launcher_icons: ^0.13.1

flutter_native_splash:
  color: "#E3ECF5"
  color_dark: "#262D35"
  android_12:
    color: "#E3ECF5"
    color_dark: "#262D35"

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "C:/Users/Akram/Downloads/coins_price.jpg"


flutter:
  uses-material-design: true

#flutter pub global activate rename
#flutter pub global run rename --bundleId com.akram.coins_price_yemen
#flutter pub global run rename --appname "أسعار العملات"